theme = "dark_plus_no_background"

[editor]
completion-replace = true
line-number = "relative"
end-of-line-diagnostics = "hint"
bufferline = "always"

[editor.inline-diagnostics]
other-lines = "error"
cursor-line = "error"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.statusline]
center = ["file-name"]
left = ["mode", "spinner"]
right = ["diagnostics", "separator", "selections", "separator", "position", "separator", "total-line-numbers", "separator", "file-line-ending", "separator", "file-type"]
separator = "|"

[editor.statusline.mode]
insert = "INSERT"
normal = "NORMAL"
select = "SELECT"
