[language-server.rust-analyzer.config]
check.command = "clippy"
cargo.allFeatures = true
file.watcher = "server"
cargo.loadOutDirsFromCheck = true

[[language]]
name = "rust"
rulers = [101]
[config.inlayHints]
bindingModeHints.enable = true
closingBraceHints.minLines = 10
closureReturnTypeHints.eanbel = "with_block"
discriminantHints.enable = "fieldless"
lifetimeElisionHints.enable = "always"
typeHints.hideClosureInitialization = false

[[language]]
name = "bash"
file-types = ["config", "sh", "bash", { glob = ".bashrc" }, { glob = ".profile" } ]

[[language]]
name = "c"
indent = { tab-width = 4, unit = " " }
