[general]
import = ["/home/mohammed/.config/alacritty/base16_default_dark.yaml"]

[cursor]
blink_interval = 750
style = "Beam"
thickness = 0.2
unfocused_hollow = true

[font]
size = 12.0
[font.bold]
family = "Jetbrains Mono"
style = "Bold"

[font.bold_italic]
family = "Jetbrains Mono"
style = "Bold Italic"

[font.italic]
family = "Jetbrains Mono"
style = "Italic"

[font.normal]
family = "Jetbrains Mono"
style = "Medium"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "nu"

[window]
opacity = 1.0

[window.padding]
x = 5
y = 5
